# Generated by Django 4.2.5 on 2024-01-26 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0012_alter_applicant_birthdate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jop',
            new_name='job',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='depart',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='jops',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='skil',
        ),
        migrations.RemoveField(
            model_name='company',
            name='depart',
        ),
        migrations.RemoveField(
            model_name='company',
            name='jops',
        ),
        migrations.RemoveField(
            model_name='education',
            name='app',
        ),
        migrations.AddField(
            model_name='applicant',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applican', to='RMS.department'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='jobs',
            field=models.ManyToManyField(related_name='applicant', to='RMS.job'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='skills',
            field=models.ManyToManyField(related_name='applicants', to='RMS.skils'),
        ),
        migrations.AddField(
            model_name='company',
            name='jobs',
            field=models.ManyToManyField(related_name='companies', to='RMS.job'),
        ),
        migrations.AddField(
            model_name='department',
            name='companies',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department', to='RMS.company'),
        ),
        migrations.AddField(
            model_name='education',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='RMS.applicant'),
        ),
        migrations.AddField(
            model_name='skils',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='OtherSection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='RMS.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='RMS.othersection')),
            ],
        ),
    ]
