# Generated by Django 4.2.5 on 2024-01-26 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0013_rename_jop_job_remove_applicant_depart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='describtion',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
