# Generated by Django 4.2.5 on 2024-01-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0016_applicant_userphoto_company_companyphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
