# Generated by Django 4.2.5 on 2024-01-30 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0022_company_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='posts',
        ),
    ]
