# Generated by Django 4.2.5 on 2024-01-30 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0023_remove_company_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='describtion',
            new_name='salray',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salay',
        ),
    ]
