# Generated by Django 4.2.5 on 2024-01-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0025_remove_job_other'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='jobs',
        ),
        migrations.AddField(
            model_name='job',
            name='companies',
            field=models.ManyToManyField(to='RMS.company'),
        ),
    ]
