# Generated by Django 4.2.5 on 2024-01-31 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0028_department_user_education_user_item_user_job_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='user',
        ),
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.RemoveField(
            model_name='othersection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skils',
            name='user',
        ),
    ]
