# Generated by Django 4.2.5 on 2024-01-31 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0029_remove_department_user_remove_education_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
    ]
