# Generated by Django 4.2.5 on 2024-02-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0032_remove_applicant_cvl_remove_applicant_jobs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='describtion',
            new_name='degree',
        ),
        migrations.AddField(
            model_name='education',
            name='fromto',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='major',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
