# Generated by Django 4.2.5 on 2024-02-01 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0034_remove_applicant_workexperience_workexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RMS.applicant'),
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='applicant',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RMS.applicant'),
        ),
    ]
