# Generated by Django 4.2.5 on 2024-02-02 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0036_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='applicant',
        ),
        migrations.AddField(
            model_name='project',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RMS.applicant'),
        ),
    ]
