# Generated by Django 4.2.5 on 2024-02-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0039_remove_project_applicant_project_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='applicant',
        ),
        migrations.AddField(
            model_name='project',
            name='applicant',
            field=models.ManyToManyField(to='RMS.applicant'),
        ),
    ]
