# Generated by Django 4.2.5 on 2024-02-04 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0040_remove_project_applicant_project_applicant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='applicants',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RMS.applicant'),
        ),
        migrations.AlterField(
            model_name='department',
            name='companies',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RMS.company'),
        ),
    ]
