# Generated by Django 4.2.5 on 2024-02-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0042_alter_company_companyphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='userphoto',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to=''),
        ),
    ]
