# Generated by Django 4.2.5 on 2024-02-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0043_alter_applicant_userphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='applicants',
        ),
        migrations.RemoveField(
            model_name='department',
            name='companies',
        ),
        migrations.AddField(
            model_name='department',
            name='applicants',
            field=models.ManyToManyField(to='RMS.applicant'),
        ),
        migrations.AddField(
            model_name='department',
            name='companies',
            field=models.ManyToManyField(to='RMS.company'),
        ),
    ]
