# Generated by Django 4.2.5 on 2024-02-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0044_remove_department_applicants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='applicants',
        ),
        migrations.RemoveField(
            model_name='department',
            name='companies',
        ),
        migrations.AddField(
            model_name='applicant',
            name='department',
            field=models.ManyToManyField(to='RMS.department'),
        ),
        migrations.AddField(
            model_name='company',
            name='department',
            field=models.ManyToManyField(to='RMS.department'),
        ),
    ]
