# Generated by Django 4.2.5 on 2024-02-05 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0045_remove_department_applicants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='department',
        ),
        migrations.AddField(
            model_name='applicant',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RMS.department'),
        ),
    ]
