# Generated by Django 4.2.5 on 2024-02-06 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0046_remove_applicant_department_applicant_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='department',
        ),
        migrations.AddField(
            model_name='company',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RMS.department'),
        ),
    ]
