# Generated by Django 4.2.5 on 2024-02-06 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0047_remove_company_department_company_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='othersection',
            name='applicant',
        ),
        migrations.AddField(
            model_name='applicant',
            name='Sections',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RMS.othersection'),
        ),
    ]
