# Generated by Django 4.2.5 on 2024-02-06 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0048_remove_othersection_applicant_applicant_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='Sections',
        ),
        migrations.AddField(
            model_name='othersection',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RMS.applicant'),
        ),
    ]
