# Generated by Django 4.2.5 on 2024-02-08 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0050_remove_item_describtion_remove_item_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'get_latest_by': 'created_at'},
        ),
    ]
