# Generated by Django 5.0.3 on 2024-03-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0051_alter_job_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birthdate',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
