# Generated by Django 5.0.3 on 2024-03-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0052_alter_applicant_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='birthdate',
            field=models.DateField(max_length=40, null=True),
        ),
    ]
