# Generated by Django 4.2.5 on 2024-04-05 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0054_jobstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='profileprofessional',
            new_name='education',
        ),
    ]
