# Generated by Django 4.2.5 on 2024-04-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0055_rename_profileprofessional_job_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='softskills',
        ),
    ]
