# Generated by Django 5.0.3 on 2024-06-22 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0056_remove_job_softskills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_companies', to=settings.AUTH_USER_MODEL),
        ),
    ]
