# Generated by Django 5.0.3 on 2024-06-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0058_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salray',
            new_name='salary',
        ),
        migrations.AddField(
            model_name='job',
            name='deletion_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
