# Generated by Django 5.0.3 on 2024-06-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RMS', '0059_rename_salray_job_salary_job_deletion_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='number_of_positions',
            field=models.IntegerField(default=1),
        ),
    ]
